name: Build and publish to RubyGems

on:
  # Run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Publish to RubyGems
      # This plugin:
      #   1. Sets up the ruby container
      #   2. Installs bundler and dependencies
      #   3. Runs `rake release`, which creates and pushes a
      #      GitHub tag based on the latest version to GitHub,
      #      and then publishes the gem to RubyGems.
      # https://github.com/marketplace/actions/publish-to-rubygems
      uses: cadwallion/publish-rubygems-action@master
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
